import './header/header';
import './sliderHome/sliderHome';
import './slider/swiperGroup/swiperGroup';
import './search/search';
// import './form/form';
// import './mask/mask';
// import './like/like';
// import './rating/rating';
// import './mobileMenu/mobileMenu';
// import './hamburger/hamburger';
import './dropdown/dropdown';
import './form/textarea/textarea';
// import './filter/filter';
// import './card/card';
// import './breadcrumbs/breadcrumbs';
import './section/contacts/contacts';
